// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-03-22 01:34:49.673167278 +0530 IST m=+0.035203876

package docs

import (
  "bytes"
  "encoding/json"
  "strings"

  "github.com/alecthomas/template"
  "github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "summary": "Get all posts"
            },
            "post": {
                "description": "Save a new post",
                "produces": [
                    "application/json"
                ],
                "summary": "Save post"
            }
        },
        "/auth/authenticate": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Authenticate user token"
            }
        },
        "/auth/login": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Login user"
            }
        },
        "/auth/register": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "summary": "Register user"
            }
        },
        "/{id}": {
            "get": {
                "description": "Get a post with given ID",
                "produces": [
                    "application/json"
                ],
                "summary": "Get post"
            },
            "put": {
                "description": "Update a post with given ID",
                "produces": [
                    "application/json"
                ],
                "summary": "Update post"
            },
            "delete": {
                "description": "Delete a post with given ID",
                "produces": [
                    "application/json"
                ],
                "summary": "Delete post"
            }
        }
    }
}`

type swaggerInfo struct {
  Version     string
  Host        string
  BasePath    string
  Schemes     []string
  Title       string
  Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
  Version:     "",
  Host:        "",
  BasePath:    "",
  Schemes:     []string{},
  Title:       "",
  Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
  sInfo := SwaggerInfo
  sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

  t, err := template.New("swagger_info").Funcs(template.FuncMap{
    "marshal": func(v interface{}) string {
      a, _ := json.Marshal(v)
      return string(a)
    },
  }).Parse(doc)
  if err != nil {
    return doc
  }

  var tpl bytes.Buffer
  if err := t.Execute(&tpl, sInfo); err != nil {
    return doc
  }

  return tpl.String()
}

func init() {
  swag.Register(swag.Name, &s{})
}
