info:
  contact: {}
  license: {}
paths:
  /:
    get:
      produces:
      - application/json
      summary: Get all posts
    post:
      description: Save a new post
      produces:
      - application/json
      summary: Save post
  /{id}:
    delete:
      description: Delete a post with given ID
      produces:
      - application/json
      summary: Delete post
    get:
      description: Get a post with given ID
      produces:
      - application/json
      summary: Get post
    put:
      description: Update a post with given ID
      produces:
      - application/json
      summary: Update post
  /auth/authenticate:
    post:
      produces:
      - application/json
      summary: Authenticate user token
  /auth/login:
    post:
      produces:
      - application/json
      summary: Login user
  /auth/register:
    post:
      produces:
      - application/json
      summary: Register user
swagger: "2.0"
